name: Boat Race AI

on:

  workflow_dispatch:

jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v4

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.x"

      - name: Convert official data

        run: python converter.py

      - name: Run AI

        run: python main.py
